// Generated by CoffeeScript 1.10.0
(function() {
  exports.getArgument = "RETURN { argument: ( FOR a IN argument FILTER a._id == @argId RETURN a )[0], premises: ( FOR v IN GRAPH_NEIGHBORS(@graphName, @argId, {edgeCollectionRestriction: 'premise'}) RETURN ( FOR s IN statement FILTER s._id == v RETURN s )[0] ), conclusion: ( FOR v IN GRAPH_NEIGHBORS(@graphName, @argId, {edgeCollectionRestriction: 'conclusion'}) RETURN ( FOR s IN statement FILTER s._id == v RETURN s )[0] )[0] }";

}).call(this);
